<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Slant.NET\MixrSharp\MixrSharp.csproj" />
      <ProjectReference Include="..\Glimpse.API\Glimpse.API.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="piko.SDL3" Version="0.0.3.1" />
      <PackageReference Include="TagLibSharp" Version="2.3.0" />
    </ItemGroup>

</Project>
