<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="Fonts/**/*" />
        <EmbeddedResource Include="Icons/**/*" />
        <EmbeddedResource Include="Images/**/*" />
        <EmbeddedResource Include="Locales/**/*" />
        <EmbeddedResource Include="Themes/**/*" />
    </ItemGroup>

</Project>
