<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <TrimMode>full</TrimMode>
        <ApplicationIcon Condition="$(Configuration) != 'Debug'">Icon.ico</ApplicationIcon>
        <ApplicationIcon Condition="$(Configuration) == 'Debug'">Icon-Dbg.ico</ApplicationIcon>
        <EnableWindowsTargeting>true</EnableWindowsTargeting>
        <VersionPrefix>0.0.0</VersionPrefix>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Hexa.NET.ImGui" Version="2.2.7" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
      <PackageReference Include="Silk.NET.OpenGL" Version="2.21.0" />
      <PackageReference Include="Silk.NET.SDL" Version="2.22.0" />
      <PackageReference Include="StbImageSharp" Version="2.27.14" />
      <PackageReference Include="TerraFX.Interop.Windows" Version="10.0.26100" />
      <PackageReference Include="Tmds.DBus" Version="0.20.0" />
    </ItemGroup>
    
    <ItemGroup>
        <EmbeddedResource Include="Graphics/Shaders/**/*" />
    </ItemGroup>
    
    <ItemGroup>
        <Content Include="Assets/**/*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Remove="Assets/Icons/Glimpse-Dbg.png" />
    </ItemGroup>
    
    <ItemGroup Condition="$(Configuration) == 'Debug'">
        <Content Remove="Assets/Icons/Glimpse.png" />
        <Content Include="Assets/Icons/Glimpse-Dbg.png">
            <Link>Assets/Icons/Glimpse.png</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\Glimpse.API\Glimpse.API.csproj" />
      <ProjectReference Include="..\..\MixrSharp\MixrSharp\MixrSharp.csproj" />
    </ItemGroup>

</Project>
