<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Glimpse.API\Glimpse.API.csproj" />
      <ProjectReference Include="..\OpenMPT.NET\OpenMPT.NET\OpenMPT.NET.csproj" />
    </ItemGroup>

</Project>
