<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <IsTrimmable>false</IsTrimmable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\MixrSharp\MixrSharp\MixrSharp.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
      <PackageReference Include="Silk.NET.SDL" Version="2.22.0" />
      <PackageReference Include="TagLibSharp" Version="2.3.0" />
    </ItemGroup>

</Project>
