name: Create Release

on:
  #workflow_dispatch:
  #  inputs:
  #    version:
  #      description: "The version of Glimpse"
  #      required: true
  #      type: string
  #    pre-release:
  #      description: "Is Pre-release?"
  #      required: true
  #      type: boolean
  release:
    types: [published]

jobs:
  publish:
    name: "Publish Glimpse $RELEASE_VERSION"
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${{ github.event.release.tag_name }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: "Install .NET"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: "Publish Windows"
        run: ./glimpsebuild.sh "Glimpse-$RELEASE_VERSION-win-x64" win-x64 $RELEASE_VERSION

      - name: "Publish Linux"
        run: ./glimpsebuild.sh "Glimpse-$RELEASE_VERSION-linux-x64" linux-x64 $RELEASE_VERSION

      - name: Create Release
        uses: ncipollo/release-action@v1.20.0
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "*.zip,*.tar.gz,*.exe"
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          #token: ${{ secrets.GITHUB_TOKEN }}
          #tag: ${{ inputs.version }}
          #generateReleaseNotes: true
          #prerelease: ${{ inputs.prerelease }}
