name: Create Release

on:
  #workflow_dispatch:
  #  inputs:
  #    version:
  #      description: "The version of Glimpse"
  #      required: true
  #      type: string
  #    pre-release:
  #      description: "Is Pre-release?"
  #      required: true
  #      type: boolean
  release:
    types: [published]

jobs:
  publish:
    name: "Publish Glimpse"
    runs-on: macos-latest
    env:
      RELEASE_VERSION: ${{ github.event.release.tag_name }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          
      - name: "Install deps"
        run: brew install nsis

      - name: "Install .NET"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: "Publish Windows x64"
        run: ./glimpsebuild.sh "Glimpse-$RELEASE_VERSION" win-x64 $RELEASE_VERSION

      - name: "Publish Linux x64"
        run: ./glimpsebuild.sh "Glimpse-$RELEASE_VERSIO" linux-x64 $RELEASE_VERSION
        
      - name: "Public macOS arm64"
        run: ./glimpsebuild.sh "Glimpse-$RELEASE_VERSION" osx-arm64 $RELEASE_VERSION

      - name: Create Release
        uses: ncipollo/release-action@v1.20.0
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "*.zip,*.tar.gz,packaging/windows/*.exe"
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          makeLatest: false
          #token: ${{ secrets.GITHUB_TOKEN }}
          #tag: ${{ inputs.version }}
          #generateReleaseNotes: true
          #prerelease: ${{ inputs.prerelease }}
